// Generated by gencpp from file motion_skapis/dualImage.msg
// DO NOT EDIT!


#ifndef MOTION_SKAPIS_MESSAGE_DUALIMAGE_H
#define MOTION_SKAPIS_MESSAGE_DUALIMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace motion_skapis
{
template <class ContainerAllocator>
struct dualImage_
{
  typedef dualImage_<ContainerAllocator> Type;

  dualImage_()
    : image1()
    , image2()  {
    }
  dualImage_(const ContainerAllocator& _alloc)
    : image1(_alloc)
    , image2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image1_type;
  _image1_type image1;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image2_type;
  _image2_type image2;





  typedef boost::shared_ptr< ::motion_skapis::dualImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_skapis::dualImage_<ContainerAllocator> const> ConstPtr;

}; // struct dualImage_

typedef ::motion_skapis::dualImage_<std::allocator<void> > dualImage;

typedef boost::shared_ptr< ::motion_skapis::dualImage > dualImagePtr;
typedef boost::shared_ptr< ::motion_skapis::dualImage const> dualImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_skapis::dualImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_skapis::dualImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_skapis::dualImage_<ContainerAllocator1> & lhs, const ::motion_skapis::dualImage_<ContainerAllocator2> & rhs)
{
  return lhs.image1 == rhs.image1 &&
    lhs.image2 == rhs.image2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_skapis::dualImage_<ContainerAllocator1> & lhs, const ::motion_skapis::dualImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_skapis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_skapis::dualImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_skapis::dualImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_skapis::dualImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_skapis::dualImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_skapis::dualImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_skapis::dualImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_skapis::dualImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5355187faf5ab03929c28f8e5fee54";
  }

  static const char* value(const ::motion_skapis::dualImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5355187faf5ab0ULL;
  static const uint64_t static_value2 = 0x3929c28f8e5fee54ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_skapis::dualImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_skapis/dualImage";
  }

  static const char* value(const ::motion_skapis::dualImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_skapis::dualImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image1\n"
"sensor_msgs/Image image2\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::motion_skapis::dualImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_skapis::dualImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image1);
      stream.next(m.image2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dualImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_skapis::dualImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_skapis::dualImage_<ContainerAllocator>& v)
  {
    s << indent << "image1: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image1);
    s << indent << "image2: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_SKAPIS_MESSAGE_DUALIMAGE_H
